"""empty message

Revision ID: 01e4e3f9fd26
Revises: f9c4f4325953
Create Date: 2020-07-22 05:45:40.571607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "01e4e3f9fd26"
down_revision = "f9c4f4325953"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operation", sa.Column("freeram", sa.Integer(), nullable=True))
    op.add_column("operation", sa.Column("net_signal", sa.Float(), nullable=True))
    op.add_column("operation", sa.Column("tasks", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operation", "tasks")
    op.drop_column("operation", "net_signal")
    op.drop_column("operation", "freeram")
    # ### end Alembic commands ###
