"""empty message

Revision ID: 0a77d70920fa
Revises: 6368d94818f1
Create Date: 2020-09-06 22:37:43.929263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0a77d70920fa"
down_revision = "6368d94818f1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operation", sa.Column("angle_x", sa.Float(), nullable=True))
    op.add_column("operation", sa.Column("angle_y", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operation", "angle_y")
    op.drop_column("operation", "angle_x")
    # ### end Alembic commands ###
