"""empty message

Revision ID: 1e2ee19acde3
Revises: f480dffe0714
Create Date: 2020-06-25 12:49:27.365108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1e2ee19acde3"
down_revision = "f480dffe0714"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operation", sa.Column("mec_power", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operation", "mec_power")
    # ### end Alembic commands ###
