"""empty message

Revision ID: 2cf0f4b7d928
Revises: d31a8eb2ebbe
Create Date: 2020-10-13 15:29:35.744116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2cf0f4b7d928"
down_revision = "d31a8eb2ebbe"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operation", sa.Column("AcX", sa.Float(), nullable=True))
    op.add_column("operation", sa.Column("AcY", sa.Float(), nullable=True))
    op.add_column("operation", sa.Column("AcZ", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operation", "AcZ")
    op.drop_column("operation", "AcY")
    op.drop_column("operation", "AcX")
    # ### end Alembic commands ###
