"""empty message

Revision ID: 482c5b9706b6
Revises: 58cac0dac67d
Create Date: 2020-05-21 19:48:23.443987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '482c5b9706b6'
down_revision = '58cac0dac67d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operation', type_='foreignkey')
    op.drop_constraint(None, 'operation', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'operation', 'vehicle', ['vehicle_id'], ['id'])
    op.create_foreign_key(None, 'operation', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
