"""empty message

Revision ID: 58cac0dac67d
Revises: 7c3281fab043
Create Date: 2020-05-21 14:32:55.108929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58cac0dac67d'
down_revision = '7c3281fab043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('rpm', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operation', 'rpm')
    # ### end Alembic commands ###
