"""empty message

Revision ID: 66142c6cd095
Revises: b278714fd81c
Create Date: 2021-02-26 03:03:43.448713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "66142c6cd095"
down_revision = "b278714fd81c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vehicle", sa.Column("activo", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicle", "activo")
    # ### end Alembic commands ###
