"""empty message

Revision ID: 7bfeb4d022a6
Revises: 34c03031997c
Create Date: 2020-08-11 15:58:20.273292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7bfeb4d022a6"
down_revision = "34c03031997c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operation", sa.Column("eff", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operation", "eff")
    # ### end Alembic commands ###
