"""empty message

Revision ID: 7c3281fab043
Revises: 9183d27c152b
Create Date: 2020-05-21 14:27:04.409796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c3281fab043'
down_revision = '9183d27c152b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('range_full', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operation', 'range_full')
    # ### end Alembic commands ###
