"""empty message

Revision ID: 826a4c3cd51b
Revises: 
Create Date: 2020-05-22 11:33:09.464190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "826a4c3cd51b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=120), nullable=True),
        sa.Column("password_hash", sa.String(length=128), nullable=True),
        sa.Column("driven_kms", sa.Integer(), nullable=True),
        sa.Column("co2_saved", sa.Integer(), nullable=True),
        sa.Column("roi", sa.Integer(), nullable=True),
        sa.Column("age", sa.Integer(), nullable=True),
        sa.Column("driving_cluster", sa.Integer(), nullable=True),
        sa.Column("charging_cluster", sa.Integer(), nullable=True),
        sa.Column("geo_cluster", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
