"""empty message

Revision ID: 8310f1eed178
Revises: e2a8f8a31656
Create Date: 2020-05-01 17:01:43.036358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8310f1eed178'
down_revision = 'e2a8f8a31656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('operative_state', sa.Integer(), nullable=True))
    op.add_column('operation', sa.Column('placa', sa.String(length=64), nullable=True))
    op.add_column('vehicle', sa.Column('odometer', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'odometer')
    op.drop_column('operation', 'placa')
    op.drop_column('operation', 'operative_state')
    # ### end Alembic commands ###
