"""add acceleration

Revision ID: 8d7d9e1b4f4f
Revises: b37ebc16b666
Create Date: 2021-09-20 19:35:12.755418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8d7d9e1b4f4f"
down_revision = "b37ebc16b666"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operation", sa.Column("acceleration", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operation", "acceleration")
    # ### end Alembic commands ###
