"""vehicles table

Revision ID: 8e7a5cf75ea1
Revises: 90816898705e
Create Date: 2020-03-28 20:25:22.577216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7a5cf75ea1'
down_revision = '90816898705e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=64), nullable=True),
    sa.Column('marca', sa.String(length=64), nullable=True),
    sa.Column('modelo', sa.String(length=64), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('capacity_nominal', sa.Float(), nullable=True),
    sa.Column('soh', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_placa'), 'vehicle', ['placa'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_placa'), table_name='vehicle')
    op.drop_table('vehicle')
    # ### end Alembic commands ###
