"""empty message

Revision ID: 9183d27c152b
Revises: 8310f1eed178
Create Date: 2020-05-21 13:13:04.389293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9183d27c152b'
down_revision = '8310f1eed178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operation', sa.Column('coulomb', sa.Float(), nullable=True))
    op.add_column('operation', sa.Column('energy', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operation', 'energy')
    op.drop_column('operation', 'coulomb')
    # ### end Alembic commands ###
