"""empty message

Revision ID: 99cc9a66425f
Revises: 4e65fafaa811
Create Date: 2020-05-22 11:35:31.194778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "99cc9a66425f"
down_revision = "4e65fafaa811"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("placa", sa.String(length=64), nullable=True),
        sa.Column("operative_state", sa.Integer(), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("elevation", sa.Float(), nullable=True),
        sa.Column("slope", sa.Float(), nullable=True),
        sa.Column("speed", sa.Integer(), nullable=True),
        sa.Column("odometer", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.String(length=64), nullable=True),
        sa.Column("batt_temp", sa.Float(), nullable=True),
        sa.Column("ext_temp", sa.Float(), nullable=True),
        sa.Column("power_kw", sa.Float(), nullable=True),
        sa.Column("acceleration", sa.Float(), nullable=True),
        sa.Column("capacity", sa.Float(), nullable=True),
        sa.Column("vehicle_id", sa.String(length=64), nullable=True),
        sa.Column("soc", sa.Float(), nullable=True),
        sa.Column("soh", sa.Float(), nullable=True),
        sa.Column("voltage", sa.Float(), nullable=True),
        sa.Column("current", sa.Float(), nullable=True),
        sa.Column("throttle", sa.Integer(), nullable=True),
        sa.Column("regen_brake", sa.Float(), nullable=True),
        sa.Column("consumption", sa.Float(), nullable=True),
        sa.Column("range_est", sa.Integer(), nullable=True),
        sa.Column("range_ideal", sa.Integer(), nullable=True),
        sa.Column("range_full", sa.Integer(), nullable=True),
        sa.Column("drivetime", sa.Integer(), nullable=True),
        sa.Column("charge_time", sa.Integer(), nullable=True),
        sa.Column("footbrake", sa.Integer(), nullable=True),
        sa.Column("engine_temp", sa.Float(), nullable=True),
        sa.Column("is_charging", sa.Integer(), nullable=True),
        sa.Column("tpms", sa.Float(), nullable=True),
        sa.Column("ocv", sa.Float(), nullable=True),
        sa.Column("coulomb", sa.Float(), nullable=True),
        sa.Column("energy", sa.Float(), nullable=True),
        sa.Column("occupants", sa.Integer(), nullable=True),
        sa.Column("rpm", sa.Integer(), nullable=True),
        sa.Column("station_id", sa.Integer(), nullable=True),
        sa.Column("sensor_data", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_operation_timestamp"), "operation", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_operation_timestamp"), table_name="operation")
    op.drop_table("operation")
    # ### end Alembic commands ###
