"""empty message

Revision ID: 9babf2a93d40
Revises: 2cf0f4b7d928
Create Date: 2020-10-31 19:47:22.229020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9babf2a93d40"
down_revision = "2cf0f4b7d928"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operation", sa.Column("humidity", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operation", "humidity")
    # ### end Alembic commands ###
