"""Add foreignKeys

Revision ID: a14b7865eb95
Revises: 80c93f8ae709
Create Date: 2021-06-04 00:09:06.080513

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "a14b7865eb95"
down_revision = "80c93f8ae709"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operation", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "operation", "user", ["user_id"], ["id"])
    op.add_column("vehicle", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "vehicle", "user", ["user_id"], ["id"])
    op.drop_column("vehicle", "belongs_to")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vehicle",
        sa.Column("belongs_to", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "vehicle", type_="foreignkey")
    op.drop_column("vehicle", "user_id")
    op.drop_constraint(None, "operation", type_="foreignkey")
    op.drop_column("operation", "user_id")
    # ### end Alembic commands ###
