"""add pressure

Revision ID: a6c45f27a93b
Revises: 61c58bbcc2dc
Create Date: 2021-06-02 23:17:52.012354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a6c45f27a93b"
down_revision = "61c58bbcc2dc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operation", sa.Column("pressure", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operation", "pressure")
    # ### end Alembic commands ###
