"""remove unused db columns

Revision ID: b37ebc16b666
Revises: f8b05ea6fd11
Create Date: 2021-09-20 00:12:12.472696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "b37ebc16b666"
down_revision = "f8b05ea6fd11"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operation", "q_loss")
    op.drop_column("operation", "occupants")
    op.drop_column("operation", "ocv")
    op.drop_column("operation", "mean_acc_server")
    op.drop_column("operation", "eff")
    op.drop_column("operation", "ilumination")
    op.drop_column("operation", "placa")
    op.drop_column("operation", "acceleration")
    op.drop_column("operation", "en_pot")
    op.drop_column("operation", "sensor_data")
    op.drop_column("operation", "mec_power_delta_e")
    op.drop_column("operation", "station_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "operation",
        sa.Column("station_id", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "operation", sa.Column("mec_power_delta_e", mysql.FLOAT(), nullable=True)
    )
    op.add_column(
        "operation",
        sa.Column(
            "sensor_data",
            mysql.VARCHAR(charset="utf8", collation="utf8_bin", length=128),
            nullable=True,
        ),
    )
    op.add_column("operation", sa.Column("en_pot", mysql.FLOAT(), nullable=True))
    op.add_column("operation", sa.Column("acceleration", mysql.FLOAT(), nullable=True))
    op.add_column(
        "operation",
        sa.Column(
            "placa",
            mysql.VARCHAR(charset="utf8", collation="utf8_bin", length=64),
            nullable=True,
        ),
    )
    op.add_column("operation", sa.Column("ilumination", mysql.FLOAT(), nullable=True))
    op.add_column("operation", sa.Column("eff", mysql.FLOAT(), nullable=True))
    op.add_column(
        "operation", sa.Column("mean_acc_server", mysql.FLOAT(), nullable=True)
    )
    op.add_column("operation", sa.Column("ocv", mysql.FLOAT(), nullable=True))
    op.add_column(
        "operation",
        sa.Column("occupants", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column("operation", sa.Column("q_loss", mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
