"""empty message

Revision ID: bda58e6c1818
Revises: 0a77d70920fa
Create Date: 2020-09-07 00:45:55.813878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bda58e6c1818"
down_revision = "0a77d70920fa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operation", sa.Column("q_loss", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operation", "q_loss")
    # ### end Alembic commands ###
