"""empty message

Revision ID: c11abf7fafdf
Revises: a5c4730dbd66
Create Date: 2020-06-06 18:59:25.971763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c11abf7fafdf"
down_revision = "a5c4730dbd66"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "operation", sa.Column("charger_type", sa.String(length=64), nullable=True)
    )
    op.add_column("operation", sa.Column("coulomb_rec", sa.Float(), nullable=True))
    op.add_column(
        "operation", sa.Column("drivemode", sa.String(length=64), nullable=True)
    )
    op.add_column("operation", sa.Column("energy_rec", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operation", "energy_rec")
    op.drop_column("operation", "drivemode")
    op.drop_column("operation", "coulomb_rec")
    op.drop_column("operation", "charger_type")
    # ### end Alembic commands ###
