"""empty message

Revision ID: d31a8eb2ebbe
Revises: fe7695034e2c
Create Date: 2020-09-08 00:11:14.908581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d31a8eb2ebbe"
down_revision = "fe7695034e2c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operation", sa.Column("ilumination", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operation", "ilumination")
    # ### end Alembic commands ###
