"""empty message

Revision ID: d3be0e0e351b
Revises: 1e2ee19acde3
Create Date: 2020-06-25 13:12:30.622019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d3be0e0e351b"
down_revision = "1e2ee19acde3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operation", sa.Column("mean_acc", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operation", "mean_acc")
    # ### end Alembic commands ###
