"""empty message

Revision ID: dd030ba1820a
Revises: efcee4e481f2
Create Date: 2020-08-04 02:52:40.215217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dd030ba1820a"
down_revision = "efcee4e481f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operation", sa.Column("mean_acc_server", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operation", "mean_acc_server")
    # ### end Alembic commands ###
