"""empty message

Revision ID: ddc0219e2064
Revises: c78a94961150
Create Date: 2020-07-05 19:40:39.053683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ddc0219e2064"
down_revision = "c78a94961150"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operation", sa.Column("friction_force", sa.Float(), nullable=True))
    op.add_column("operation", sa.Column("net_force", sa.Float(), nullable=True))
    op.add_column("operation", sa.Column("run", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operation", "run")
    op.drop_column("operation", "net_force")
    op.drop_column("operation", "friction_force")
    # ### end Alembic commands ###
