"""empty message

Revision ID: efcee4e481f2
Revises: 01e4e3f9fd26
Create Date: 2020-08-03 18:22:17.148088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "efcee4e481f2"
down_revision = "01e4e3f9fd26"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operation", sa.Column("elevation2", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operation", "elevation2")
    # ### end Alembic commands ###
