"""empty message

Revision ID: f480dffe0714
Revises: c11abf7fafdf
Create Date: 2020-06-25 10:39:50.825550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f480dffe0714"
down_revision = "c11abf7fafdf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operation", sa.Column("mass", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operation", "mass")
    # ### end Alembic commands ###
