"""eliminate task relation

Revision ID: f8b05ea6fd11
Revises: a14b7865eb95
Create Date: 2021-08-24 18:41:51.401967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "f8b05ea6fd11"
down_revision = "a14b7865eb95"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_task_name", table_name="task")
    op.drop_table("task")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task",
        sa.Column("id", mysql.VARCHAR(collation="utf8_bin", length=36), nullable=False),
        sa.Column(
            "name", mysql.VARCHAR(collation="utf8_bin", length=128), nullable=True
        ),
        sa.Column(
            "description",
            mysql.VARCHAR(collation="utf8_bin", length=128),
            nullable=True,
        ),
        sa.Column("user_id", mysql.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "complete",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=True,
        ),
        sa.CheckConstraint("(`complete` in (0,1))", name="task_chk_1"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="task_ibfk_1"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8_bin",
        mysql_default_charset="utf8",
        mysql_engine="InnoDB",
    )
    op.create_index("ix_task_name", "task", ["name"], unique=False)
    # ### end Alembic commands ###
