"""empty message

Revision ID: f9c4f4325953
Revises: 101d4a8418b5
Create Date: 2020-07-19 16:46:18.000065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f9c4f4325953"
down_revision = "101d4a8418b5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("operation", sa.Column("mean_speed", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("operation", "mean_speed")
    # ### end Alembic commands ###
